### ISSUE TITLE
You need a obsfu ?

### ISSUE THREAD

**Issue by Osaraxi** [MIM-104/Overhaul#1]
Good Work I see for scp lua script you need a obsfu  here one luaobfuscator.com if u was aleardy using but its not working anymore since new update use that : 
![image](https://github.com/user-attachments/assets/b0794851-b69d-4e80-8692-179fce566d6c)

**Comment by MIM-104** [comment]
I won't be using that since it's already been decompiled, and the script contains webhook links which i wouldn't like to make public for safety purposes. I was normally using prometheus, but it recently got decompiled too (due to its source being right there). Thanks for the issue though!
